blank_issues_enabled: true
contact_links:
    - name: 📝 Code of Conduct
      url: https://github.com/aperowebnancy/aperowebnancy-website/blob/main/.github/CODE_OF_CONDUCT.md
      about: ❤ Be nice to other members of the community. ☮ Behave.
